version: '3.7'

services:

  server:
    build:
      context: .
      dockerfile: ./Dockerfiles/server/Dockerfile
    image: server
    container_name: GophKeeper_server
    restart: always
    environment:
      - SERVER_ADDRESS=server:8080
      - LOG_LEVEL=Info
      - DATABASE_DSN=postgres://gophkeeperdb:gophkeeperdbpwd@postgres_db:5432/gophkeeperdb?sslmode=disable
      - SECRET=supersecret
      - ISSECURE=true
      - ENDPOINTMINIO=minio:9000
      - ACCESSKEYIDMINIO=masoud
      - SECRETACCESSKEYMINIO=Strong#Pass#2022
      - BUCKETNAMEMINIO=secrets
      - ISUSESSLMINIO=false
    ports:
      - 50051:50051
    depends_on:
      - postgres_db
      - minio


  postgres_db:
    image: postgres:15.3
    container_name: GophKeeper_postgres_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=gophkeeperdbpwd
      - POSTGRES_USER=gophkeeperdb
      - POSTGRES_DB=gophkeeperdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7.5
    container_name: GophKeeper_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: go@go.go
      PGADMIN_DEFAULT_PASSWORD: go
    volumes:
      - ./pgadmindata/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres_db

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data


volumes:
  pg_data: {}
  minio_storage: {}