version: '3.7'

services:

  server:
    build:
      context: .
      dockerfile: ./Dockerfiles/server/Dockerfile
    image: server
    container_name: GophKeeper_server
    restart: always
    environment:
      - RUN_ADDRESS=server:8080
      - DATABASE_URI=postgres://gophkeeperdb:gophkeeperdbpwd@postgres_db:5432/gophkeeperdb?sslmode=disable
      - LOGGER_LEVEL=Debug
    depends_on:
      - postgres_db


  postgres_db:
    image: postgres:15.3
    container_name: GophKeeper_postgres_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=gophkeeperdbpwd
      - POSTGRES_USER=gophkeeperdb
      - POSTGRES_DB=gophkeeperdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7.5
    container_name: GophKeeper_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: go@go.go
      PGADMIN_DEFAULT_PASSWORD: go
    volumes:
      - ./pgadmindata/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres_db


volumes:
  pg_data: { }