// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/client/infrastrucrure/filemanager/filemanager.go

// Package mock_filemanager is a generated GoMock package.
package mock_filemanager

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	filemanager "github.com/kripsy/GophKeeper/internal/client/infrastrucrure/filemanager"
	models "github.com/kripsy/GophKeeper/internal/models"
)

// MockFileStorage is a mock of FileStorage interface.
type MockFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageMockRecorder
}

// MockFileStorageMockRecorder is the mock recorder for MockFileStorage.
type MockFileStorageMockRecorder struct {
	mock *MockFileStorage
}

// NewMockFileStorage creates a new mock instance.
func NewMockFileStorage(ctrl *gomock.Controller) *MockFileStorage {
	mock := &MockFileStorage{ctrl: ctrl}
	mock.recorder = &MockFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorage) EXPECT() *MockFileStorageMockRecorder {
	return m.recorder
}

// AddEncryptedToStorage mocks base method.
func (m *MockFileStorage) AddEncryptedToStorage(name string, data chan []byte, info models.DataInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEncryptedToStorage", name, data, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEncryptedToStorage indicates an expected call of AddEncryptedToStorage.
func (mr *MockFileStorageMockRecorder) AddEncryptedToStorage(name, data, info interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEncryptedToStorage", reflect.TypeOf((*MockFileStorage)(nil).AddEncryptedToStorage), name, data, info)
}

// AddToStorage mocks base method.
func (m *MockFileStorage) AddToStorage(name string, data filemanager.Data, info models.DataInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToStorage", name, data, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToStorage indicates an expected call of AddToStorage.
func (mr *MockFileStorageMockRecorder) AddToStorage(name, data, info interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToStorage", reflect.TypeOf((*MockFileStorage)(nil).AddToStorage), name, data, info)
}

// DeleteByIOs mocks base method.
func (m *MockFileStorage) DeleteByIDs(ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByIDs", ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByIOs indicates an expected call of DeleteByIOs.
func (mr *MockFileStorageMockRecorder) DeleteByIOs(ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByIDs", reflect.TypeOf((*MockFileStorage)(nil).DeleteByIDs), ids)
}

// DeleteByName mocks base method.
func (m *MockFileStorage) DeleteByName(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByName", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByName indicates an expected call of DeleteByName.
func (mr *MockFileStorageMockRecorder) DeleteByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByName", reflect.TypeOf((*MockFileStorage)(nil).DeleteByName), name)
}

// GetByName mocks base method.
func (m *MockFileStorage) GetByName(name string) ([]byte, models.DataInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", name)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(models.DataInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByName indicates an expected call of GetByName.
func (mr *MockFileStorageMockRecorder) GetByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockFileStorage)(nil).GetByName), name)
}

// ReadEncryptedByName mocks base method.
func (m *MockFileStorage) ReadEncryptedByName(name string) (chan []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadEncryptedByName", name)
	ret0, _ := ret[0].(chan []byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadEncryptedByName indicates an expected call of ReadEncryptedByName.
func (mr *MockFileStorageMockRecorder) ReadEncryptedByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEncryptedByName", reflect.TypeOf((*MockFileStorage)(nil).ReadEncryptedByName), name)
}

// UpdateDataByName mocks base method.
func (m *MockFileStorage) UpdateDataByName(name string, data filemanager.Data) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataByName", name, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDataByName indicates an expected call of UpdateDataByName.
func (mr *MockFileStorageMockRecorder) UpdateDataByName(name, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataByName", reflect.TypeOf((*MockFileStorage)(nil).UpdateDataByName), name, data)
}

// UpdateInfoByName mocks base method.
func (m *MockFileStorage) UpdateInfoByName(name string, info models.DataInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInfoByName", name, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInfoByName indicates an expected call of UpdateInfoByName.
func (mr *MockFileStorageMockRecorder) UpdateInfoByName(name, info interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInfoByName", reflect.TypeOf((*MockFileStorage)(nil).UpdateInfoByName), name, info)
}
