version: '3.7'

services:
  

  migration_db_up:
    image: migrate/migrate:v4.16.2
    command:
      [
        "-path", "/migrations",
        "-database" , "postgres://gophkeeperdb:gophkeeperdbpwd@docker.for.mac.localhost:5432/gophkeeperdb?sslmode=disable",
        "up"
        ]
    volumes:
      - ../internal/infrastructure/migrations:/migrations

  

  migration_db_down:
    image: migrate/migrate:v4.16.2
    command:
      [
        "-path", "/migrations",
        "-database" , "postgres://gophkeeperdb:gophkeeperdbpwd@docker.for.mac.localhost:5432/gophkeeperdb?sslmode=disable",
        "down", "-all",
        ]
    volumes:
      - ../internal/infrastructure/migrations:/migrations


  migration_db_force:
    image: migrate/migrate:v4.16.2
    command:
      [
        "-path", "/migrations",
        "-database" , "postgres://gophkeeperdb:gophkeeperdbpwd@docker.for.mac.localhost:5432/gophkeeperdb?sslmode=disable",
        "force", "1"
        ]
    volumes:
      - ../internal/infrastructure/migrations:/migrations



  migration_db_add:
    image: migrate/migrate:v4.16.2
    command:
      [
        "create",
        "-dir", "/migrations",
        "-ext", ".sql",
        "-seq", "-digits", "5",
        "init_migration"
      ]
    volumes:
      - ../internal/infrastructure/migrations:/migrations
